namespace: prod
commonLabels:
  env: prod
bases:
- https://github.com/agmsbush/gke-dev-to-prod-blueprints/resources
patchesStrategicMerge:
- deployment.yaml
configMapGenerator:
  - name: alpha-features
    literals:    
    - ENABLE_ALPHA="false"